/**
 * SJI Fire & Rescue Operations Dashboard
 *
 * Generated by Claude.ai using live data from the SJI Fire MCP server.
 * This is a design reference showing how dispatch calls, duty crew, and
 * incident data can be visualized. Data shape matches what the MCP tools
 * return (get_on_duty_crew, list_dispatch_calls, get_dispatch_call,
 * list_incidents).
 *
 * To preview: paste into a Claude.ai artifact or any React sandbox.
 *
 * Tabs:
 *   Overview  — stats cards, crew summary, recent calls
 *   Calls     — dispatch log table with severity indicators
 *   Crew      — on-duty roster grouped by section
 *   Reporting — incident report status, calls missing reports
 */

import { useState } from "react";

const LOGO_URL = "https://res.cloudinary.com/san-juan-fire-district-3/image/fetch/f_auto/https://www.sjifire.org/assets/sjifire-logo-clear.png";

const crewData = [
  { name: "Kyle Dodd", position: "Captain", section: "S31", shift: "0800–1800", isDay: true },
  { name: "Stephen Chadwick", position: "Lieutenant", section: "S31", shift: "1800–1800", isDay: false },
  { name: "Brad Smith", position: "Apparatus Operator", section: "S31", shift: "1800–1800", isDay: false },
  { name: "Jordan Pollack", position: "Chief", section: "Chief", shift: "1800–1800", isDay: false },
  { name: "Matthew Wickey", position: "Marine: Mate", section: "FB31", shift: "1800–1500", isDay: false },
  { name: "Charles Genther", position: "Support", section: "Support", shift: "1800–1800", isDay: false },
];

const recentCalls = [
  {
    id: "26-002134",
    nature: "Fire-Structure",
    address: "GPS Coords Only",
    date: "Feb 12",
    time: "14:38",
    units: "—",
    status: "completed",
    note: "No units / possible test",
    severity: "low",
  },
  {
    id: "26-002059",
    nature: "CPR ALS",
    address: "72 Myers Rd",
    date: "Feb 10",
    time: "22:47",
    units: "E31, BN31, M12, EMS12",
    status: "completed",
    note: "72yo syncope → airlift LFNW",
    severity: "high",
  },
  {
    id: "26-001980",
    nature: "Accident-Injury",
    address: "Roche Harbor Rd & West Valley Rd",
    date: "Feb 8",
    time: "22:04",
    units: "E31, BN31, R31, M12, EMS12, OPS31",
    status: "completed",
    note: "Rollover MVA → airlift LFNW",
    severity: "high",
  },
  {
    id: "26-001927",
    nature: "Fire-Chimney",
    address: "105 Petrich Rd",
    date: "Feb 7",
    time: "13:45",
    units: "E31, BN31, OPS31, E33, E35, L31, T33",
    status: "completed",
    note: "Chimney fire, confined, extinguished",
    severity: "medium",
  },
  {
    id: "26-001913",
    nature: "Fire-Alarm",
    address: "1785 Douglas Rd #45",
    date: "Feb 7",
    time: "01:42",
    units: "E31, BN31, T33",
    status: "completed",
    note: "Stove alarm, source located, all clear",
    severity: "low",
  },
];

const severityColor = {
  high: "#dc2626",
  medium: "#f59e0b",
  low: "#6b7280",
};

const severityBg = {
  high: "rgba(220,38,38,0.1)",
  medium: "rgba(245,158,11,0.08)",
  low: "rgba(107,114,128,0.08)",
};

const natureIcon = (nature) => {
  if (nature.includes("CPR") || nature.includes("ALS")) return "🚑";
  if (nature.includes("Accident")) return "🚗";
  if (nature.includes("Structure")) return "🔥";
  if (nature.includes("Chimney")) return "🏠";
  if (nature.includes("Alarm")) return "🔔";
  return "📟";
};

export default function SJIFireDashboard() {
  const [activeTab, setActiveTab] = useState("overview");
  const now = new Date();
  const currentHour = now.getHours();
  const isBusinessHours = currentHour >= 8 && currentHour < 18;

  return (
    <div style={{
      minHeight: "100vh",
      background: "#0c1829",
      fontFamily: "'Segoe UI', 'Helvetica Neue', sans-serif",
      color: "#e2e8f0",
    }}>
      {/* Header */}
      <header style={{
        background: "linear-gradient(135deg, #0f2240 0%, #1a3a5c 100%)",
        borderBottom: "3px solid #b91c1c",
        padding: "0",
      }}>
        <div style={{
          maxWidth: 1200,
          margin: "0 auto",
          padding: "12px 24px",
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
        }}>
          <div style={{ display: "flex", alignItems: "center", gap: 16 }}>
            <img
              src={LOGO_URL}
              alt="SJIF&R Logo"
              style={{ height: 52, filter: "brightness(1.1)" }}
              onError={(e) => { e.target.style.display = "none"; }}
            />
            <div>
              <div style={{
                fontSize: 20,
                fontWeight: 700,
                color: "#ffffff",
                letterSpacing: "0.02em",
                lineHeight: 1.2,
              }}>
                Operations Dashboard
              </div>
              <div style={{
                fontSize: 11,
                color: "#94a3b8",
                letterSpacing: "0.08em",
                textTransform: "uppercase",
                marginTop: 2,
              }}>
                San Juan Island Fire & Rescue
              </div>
            </div>
          </div>
          <div style={{ textAlign: "right" }}>
            <div style={{
              fontSize: 13,
              color: "#94a3b8",
            }}>
              {now.toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric", year: "numeric" })}
            </div>
            <div style={{
              display: "inline-flex",
              alignItems: "center",
              gap: 6,
              marginTop: 4,
              background: "rgba(34,197,94,0.15)",
              border: "1px solid rgba(34,197,94,0.3)",
              borderRadius: 20,
              padding: "3px 12px",
              fontSize: 12,
              color: "#4ade80",
              fontWeight: 600,
            }}>
              <span style={{
                width: 7,
                height: 7,
                borderRadius: "50%",
                background: "#4ade80",
                display: "inline-block",
                animation: "pulse 2s ease-in-out infinite",
              }} />
              No Active Calls
            </div>
          </div>
        </div>
      </header>

      {/* Nav Tabs */}
      <nav style={{
        background: "#111d32",
        borderBottom: "1px solid rgba(255,255,255,0.06)",
      }}>
        <div style={{
          maxWidth: 1200,
          margin: "0 auto",
          padding: "0 24px",
          display: "flex",
          gap: 0,
        }}>
          {["overview", "calls", "crew", "reporting"].map((tab) => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              style={{
                background: "none",
                border: "none",
                borderBottom: activeTab === tab ? "2px solid #b91c1c" : "2px solid transparent",
                color: activeTab === tab ? "#ffffff" : "#64748b",
                padding: "12px 20px",
                fontSize: 13,
                fontWeight: 600,
                cursor: "pointer",
                textTransform: "uppercase",
                letterSpacing: "0.06em",
                transition: "all 0.2s",
              }}
            >
              {{ overview: "Overview", calls: "Recent Calls", crew: "On Duty", reporting: "Reporting" }[tab]}
            </button>
          ))}
        </div>
      </nav>

      {/* Content */}
      <main style={{
        maxWidth: 1200,
        margin: "0 auto",
        padding: "24px",
      }}>

        {/* OVERVIEW TAB */}
        {activeTab === "overview" && (
          <div>
            {/* Stats Row */}
            <div style={{
              display: "grid",
              gridTemplateColumns: "repeat(4, 1fr)",
              gap: 16,
              marginBottom: 24,
            }}>
              {[
                { label: "Open Calls", value: "0", accent: "#4ade80", sub: "All clear" },
                { label: "On Duty", value: "6", accent: "#60a5fa", sub: "A Platoon" },
                { label: "Calls (7 days)", value: "5", accent: "#f59e0b", sub: "2 airlifts" },
                { label: "Duty Officer", value: "Pollack", accent: "#c084fc", sub: "Chief Officer" },
              ].map((stat, i) => (
                <div key={i} style={{
                  background: "linear-gradient(135deg, #162033 0%, #1a2744 100%)",
                  border: "1px solid rgba(255,255,255,0.06)",
                  borderRadius: 8,
                  padding: "20px 18px",
                  borderLeft: `3px solid ${stat.accent}`,
                }}>
                  <div style={{ fontSize: 11, color: "#64748b", textTransform: "uppercase", letterSpacing: "0.08em", marginBottom: 8 }}>
                    {stat.label}
                  </div>
                  <div style={{ fontSize: 28, fontWeight: 700, color: "#ffffff", lineHeight: 1 }}>
                    {stat.value}
                  </div>
                  <div style={{ fontSize: 12, color: "#94a3b8", marginTop: 6 }}>
                    {stat.sub}
                  </div>
                </div>
              ))}
            </div>

            {/* Two column: Crew + Recent */}
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1.6fr", gap: 20 }}>
              {/* Crew Panel */}
              <div style={{
                background: "#162033",
                border: "1px solid rgba(255,255,255,0.06)",
                borderRadius: 8,
                overflow: "hidden",
              }}>
                <div style={{
                  padding: "14px 18px",
                  borderBottom: "1px solid rgba(255,255,255,0.06)",
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "center",
                }}>
                  <span style={{ fontSize: 14, fontWeight: 600, color: "#ffffff" }}>On Duty — A Platoon</span>
                  <span style={{ fontSize: 11, color: "#64748b" }}>Feb 12, 2026</span>
                </div>
                {crewData.map((c, i) => (
                  <div key={i} style={{
                    padding: "12px 18px",
                    borderBottom: i < crewData.length - 1 ? "1px solid rgba(255,255,255,0.04)" : "none",
                    display: "flex",
                    justifyContent: "space-between",
                    alignItems: "center",
                  }}>
                    <div>
                      <div style={{ fontSize: 13, fontWeight: 600, color: "#e2e8f0" }}>{c.name}</div>
                      <div style={{ fontSize: 11, color: "#64748b", marginTop: 2 }}>{c.position}</div>
                    </div>
                    <div style={{ textAlign: "right" }}>
                      <span style={{
                        fontSize: 11,
                        background: "rgba(96,165,250,0.12)",
                        color: "#60a5fa",
                        padding: "2px 8px",
                        borderRadius: 4,
                        fontWeight: 600,
                      }}>
                        {c.section}
                      </span>
                    </div>
                  </div>
                ))}
              </div>

              {/* Recent Calls */}
              <div style={{
                background: "#162033",
                border: "1px solid rgba(255,255,255,0.06)",
                borderRadius: 8,
                overflow: "hidden",
              }}>
                <div style={{
                  padding: "14px 18px",
                  borderBottom: "1px solid rgba(255,255,255,0.06)",
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "center",
                }}>
                  <span style={{ fontSize: 14, fontWeight: 600, color: "#ffffff" }}>Recent Calls — Last 7 Days</span>
                  <span style={{ fontSize: 11, color: "#64748b" }}>5 calls</span>
                </div>
                {recentCalls.map((call, i) => (
                  <div key={i} style={{
                    padding: "14px 18px",
                    borderBottom: i < recentCalls.length - 1 ? "1px solid rgba(255,255,255,0.04)" : "none",
                    borderLeft: `3px solid ${severityColor[call.severity]}`,
                    background: severityBg[call.severity],
                  }}>
                    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}>
                      <div style={{ display: "flex", gap: 10, alignItems: "flex-start" }}>
                        <span style={{ fontSize: 20, lineHeight: 1 }}>{natureIcon(call.nature)}</span>
                        <div>
                          <div style={{ fontSize: 13, fontWeight: 600, color: "#e2e8f0" }}>
                            {call.nature}
                          </div>
                          <div style={{ fontSize: 12, color: "#94a3b8", marginTop: 2 }}>
                            {call.address}
                          </div>
                          <div style={{ fontSize: 11, color: "#64748b", marginTop: 4 }}>
                            {call.note}
                          </div>
                        </div>
                      </div>
                      <div style={{ textAlign: "right", flexShrink: 0 }}>
                        <div style={{ fontSize: 12, color: "#94a3b8", fontWeight: 600 }}>{call.date}</div>
                        <div style={{ fontSize: 11, color: "#64748b" }}>{call.time}</div>
                        <div style={{
                          fontSize: 10,
                          color: "#475569",
                          marginTop: 4,
                          fontFamily: "monospace",
                        }}>
                          {call.id}
                        </div>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}

        {/* CALLS TAB */}
        {activeTab === "calls" && (
          <div>
            <div style={{
              background: "#162033",
              border: "1px solid rgba(255,255,255,0.06)",
              borderRadius: 8,
              overflow: "hidden",
            }}>
              <div style={{
                padding: "14px 18px",
                borderBottom: "1px solid rgba(255,255,255,0.06)",
              }}>
                <span style={{ fontSize: 14, fontWeight: 600, color: "#ffffff" }}>Dispatch Log — Last 7 Days</span>
              </div>
              <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 13 }}>
                <thead>
                  <tr style={{ borderBottom: "1px solid rgba(255,255,255,0.08)" }}>
                    {["", "Dispatch ID", "Date/Time", "Nature", "Address", "Units", "Notes"].map((h) => (
                      <th key={h} style={{
                        padding: "10px 14px",
                        textAlign: "left",
                        fontSize: 11,
                        color: "#64748b",
                        textTransform: "uppercase",
                        letterSpacing: "0.06em",
                        fontWeight: 600,
                      }}>{h}</th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {recentCalls.map((call, i) => (
                    <tr key={i} style={{
                      borderBottom: "1px solid rgba(255,255,255,0.04)",
                      background: i % 2 === 0 ? "transparent" : "rgba(255,255,255,0.015)",
                    }}>
                      <td style={{ padding: "12px 14px", width: 30 }}>
                        <span style={{
                          width: 8,
                          height: 8,
                          borderRadius: "50%",
                          background: severityColor[call.severity],
                          display: "inline-block",
                        }} />
                      </td>
                      <td style={{ padding: "12px 14px", fontFamily: "monospace", color: "#94a3b8", fontSize: 12 }}>{call.id}</td>
                      <td style={{ padding: "12px 14px", color: "#e2e8f0" }}>{call.date} {call.time}</td>
                      <td style={{ padding: "12px 14px", color: "#ffffff", fontWeight: 600 }}>
                        {natureIcon(call.nature)} {call.nature}
                      </td>
                      <td style={{ padding: "12px 14px", color: "#94a3b8" }}>{call.address}</td>
                      <td style={{ padding: "12px 14px", color: "#64748b", fontSize: 11 }}>{call.units}</td>
                      <td style={{ padding: "12px 14px", color: "#64748b", fontSize: 12 }}>{call.note}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {/* CREW TAB */}
        {activeTab === "crew" && (
          <div>
            <div style={{
              background: "#162033",
              border: "1px solid rgba(255,255,255,0.06)",
              borderRadius: 8,
              overflow: "hidden",
            }}>
              <div style={{
                padding: "14px 18px",
                borderBottom: "1px solid rgba(255,255,255,0.06)",
                display: "flex",
                justifyContent: "space-between",
                alignItems: "center",
              }}>
                <span style={{ fontSize: 14, fontWeight: 600, color: "#ffffff" }}>A Platoon — February 12, 2026</span>
                <span style={{
                  fontSize: 11,
                  background: isBusinessHours ? "rgba(34,197,94,0.15)" : "rgba(96,165,250,0.12)",
                  color: isBusinessHours ? "#4ade80" : "#60a5fa",
                  padding: "3px 10px",
                  borderRadius: 4,
                  fontWeight: 600,
                }}>
                  {isBusinessHours ? "Day Shift Active" : "Night Shift Active"}
                </span>
              </div>

              {["S31", "Chief", "FB31", "Support"].map((section) => {
                const members = crewData.filter((c) => c.section === section);
                if (members.length === 0) return null;
                return (
                  <div key={section}>
                    <div style={{
                      padding: "8px 18px",
                      background: "rgba(255,255,255,0.02)",
                      borderBottom: "1px solid rgba(255,255,255,0.04)",
                      fontSize: 11,
                      color: "#64748b",
                      textTransform: "uppercase",
                      letterSpacing: "0.08em",
                      fontWeight: 600,
                    }}>
                      {section === "S31" ? "Station 31" : section === "FB31" ? "Fireboat 31 Standby" : section === "Chief" ? "Chief Officer" : "Support Standby"}
                    </div>
                    {members.map((c, j) => (
                      <div key={j} style={{
                        padding: "14px 18px",
                        borderBottom: "1px solid rgba(255,255,255,0.04)",
                        display: "grid",
                        gridTemplateColumns: "2fr 1.2fr 1fr",
                        alignItems: "center",
                      }}>
                        <div>
                          <span style={{ fontSize: 14, fontWeight: 600, color: "#e2e8f0" }}>{c.name}</span>
                        </div>
                        <div>
                          <span style={{
                            fontSize: 12,
                            background: c.position === "Captain" ? "rgba(220,38,38,0.15)" :
                              c.position === "Lieutenant" ? "rgba(245,158,11,0.12)" :
                              c.position === "Chief" ? "rgba(192,132,252,0.12)" :
                              "rgba(96,165,250,0.10)",
                            color: c.position === "Captain" ? "#f87171" :
                              c.position === "Lieutenant" ? "#fbbf24" :
                              c.position === "Chief" ? "#c084fc" :
                              "#60a5fa",
                            padding: "3px 10px",
                            borderRadius: 4,
                            fontWeight: 600,
                          }}>
                            {c.position}
                          </span>
                        </div>
                        <div style={{ textAlign: "right" }}>
                          <span style={{ fontSize: 12, color: "#64748b", fontFamily: "monospace" }}>
                            {c.shift}
                          </span>
                        </div>
                      </div>
                    ))}
                  </div>
                );
              })}
            </div>
          </div>
        )}
        {/* REPORTING TAB */}
        {activeTab === "reporting" && (
          <div>
            {/* Summary badges */}
            <div style={{
              display: "grid",
              gridTemplateColumns: "repeat(3, 1fr)",
              gap: 16,
              marginBottom: 24,
            }}>
              {[
                { label: "In Progress", value: "0", accent: "#60a5fa", sub: "Drafts & reviews" },
                { label: "Calls Missing Reports", value: "5", accent: "#f59e0b", sub: "Last 7 days" },
                { label: "Ready to Submit", value: "0", accent: "#4ade80", sub: "Awaiting officer review" },
              ].map((stat, i) => (
                <div key={i} style={{
                  background: "linear-gradient(135deg, #162033 0%, #1a2744 100%)",
                  border: "1px solid rgba(255,255,255,0.06)",
                  borderRadius: 8,
                  padding: "20px 18px",
                  borderLeft: `3px solid ${stat.accent}`,
                }}>
                  <div style={{ fontSize: 11, color: "#64748b", textTransform: "uppercase", letterSpacing: "0.08em", marginBottom: 8 }}>
                    {stat.label}
                  </div>
                  <div style={{ fontSize: 28, fontWeight: 700, color: "#ffffff", lineHeight: 1 }}>
                    {stat.value}
                  </div>
                  <div style={{ fontSize: 12, color: "#94a3b8", marginTop: 6 }}>
                    {stat.sub}
                  </div>
                </div>
              ))}
            </div>

            {/* In-Progress Reports */}
            <div style={{
              background: "#162033",
              border: "1px solid rgba(255,255,255,0.06)",
              borderRadius: 8,
              overflow: "hidden",
              marginBottom: 20,
            }}>
              <div style={{
                padding: "14px 18px",
                borderBottom: "1px solid rgba(255,255,255,0.06)",
                display: "flex",
                justifyContent: "space-between",
                alignItems: "center",
              }}>
                <span style={{ fontSize: 14, fontWeight: 600, color: "#ffffff" }}>In-Progress Reports</span>
                <span style={{
                  fontSize: 11,
                  background: "rgba(96,165,250,0.12)",
                  color: "#60a5fa",
                  padding: "3px 10px",
                  borderRadius: 4,
                  fontWeight: 600,
                }}>
                  Draft · In Progress · Ready for Review
                </span>
              </div>
              <div style={{
                padding: "32px 18px",
                textAlign: "center",
                color: "#475569",
                fontSize: 13,
              }}>
                No incident reports in progress.
              </div>
            </div>

            {/* Calls Missing After-Action Reports */}
            <div style={{
              background: "#162033",
              border: "1px solid rgba(255,255,255,0.06)",
              borderRadius: 8,
              overflow: "hidden",
            }}>
              <div style={{
                padding: "14px 18px",
                borderBottom: "1px solid rgba(255,255,255,0.06)",
                display: "flex",
                justifyContent: "space-between",
                alignItems: "center",
              }}>
                <span style={{ fontSize: 14, fontWeight: 600, color: "#ffffff" }}>Calls Missing Reports</span>
                <span style={{
                  fontSize: 11,
                  background: "rgba(245,158,11,0.12)",
                  color: "#fbbf24",
                  padding: "3px 10px",
                  borderRadius: 4,
                  fontWeight: 600,
                }}>
                  5 calls need attention
                </span>
              </div>
              <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 13 }}>
                <thead>
                  <tr style={{ borderBottom: "1px solid rgba(255,255,255,0.08)" }}>
                    {["", "Dispatch ID", "Date", "Nature", "Address", "Status"].map((h) => (
                      <th key={h} style={{
                        padding: "10px 14px",
                        textAlign: "left",
                        fontSize: 11,
                        color: "#64748b",
                        textTransform: "uppercase",
                        letterSpacing: "0.06em",
                        fontWeight: 600,
                      }}>{h}</th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {recentCalls.map((call, i) => (
                    <tr key={i} style={{
                      borderBottom: "1px solid rgba(255,255,255,0.04)",
                      background: i % 2 === 0 ? "transparent" : "rgba(255,255,255,0.015)",
                    }}>
                      <td style={{ padding: "12px 14px", width: 30 }}>
                        <span style={{
                          width: 8,
                          height: 8,
                          borderRadius: "50%",
                          background: severityColor[call.severity],
                          display: "inline-block",
                        }} />
                      </td>
                      <td style={{ padding: "12px 14px", fontFamily: "monospace", color: "#94a3b8", fontSize: 12 }}>{call.id}</td>
                      <td style={{ padding: "12px 14px", color: "#e2e8f0" }}>{call.date} {call.time}</td>
                      <td style={{ padding: "12px 14px", color: "#ffffff", fontWeight: 600 }}>
                        {natureIcon(call.nature)} {call.nature}
                      </td>
                      <td style={{ padding: "12px 14px", color: "#94a3b8" }}>{call.address}</td>
                      <td style={{ padding: "12px 14px" }}>
                        <span style={{
                          fontSize: 11,
                          background: "rgba(245,158,11,0.12)",
                          color: "#fbbf24",
                          padding: "3px 10px",
                          borderRadius: 4,
                          fontWeight: 600,
                        }}>
                          No Report
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

      </main>

      {/* Footer */}
      <footer style={{
        maxWidth: 1200,
        margin: "0 auto",
        padding: "16px 24px 32px",
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        fontSize: 11,
        color: "#475569",
      }}>
        <span>San Juan County Fire District 3 · 1011 Mullis Street, Friday Harbor, WA 98250</span>
        <span>© 2026 SJIF&R</span>
      </footer>

      <style>{`
        @keyframes pulse {
          0%, 100% { opacity: 1; }
          50% { opacity: 0.4; }
        }
        * { box-sizing: border-box; margin: 0; padding: 0; }
        button:hover { opacity: 0.85; }
      `}</style>
    </div>
  );
}
